### PR TITLE
[ENH] switch tqdm for rich progress bar

### LINKED ISSUE #94: use Rich progress bars
would allow to drop one dependency

see https://rich.readthedocs.io/en/stable/progress.html#basic-usage

```
import time
from rich.progress import track

for i in track(range(20), description="Processing..."):
    time.sleep(1) 
```

image

### PR DESCRIPTION
**Pull request by Remi-Gau**
close #94

### CODE REVIEW

**Comment by htwangtw** [comment]
Fixed `mist2templateflow` and hopefully this will fix it

**Comment by htwangtw** [comment]
merging the current main branch should fix it

**Comment by Remi-Gau** [comment]
all tests pass: should be good to merge

**Review by htwangtw — APPROVED** [review]
Test passed, all good

**Pull request merged**
