### PR TITLE
[MAINT] bump nilearn version to 0.10.2

### LINKED ISSUE #26: ValueError: Could not find associated confound file. The functional derivatives should exist under the same parent directory.
Entity `acq` cannot be recongnised correctly

This is an upstream issue. Will be fix by the next release of nilearn

Open issue for book keeping.

Dataset: abide2 ONRC_2

https://github.com/nilearn/nilearn/pull/3794

### LINKED ISSUE #27: Missing cosine regressors in some output
Upstream issue. See: https://github.com/nilearn/nilearn/issues/3537

### PR DESCRIPTION
**Pull request by Remi-Gau**
- closes #26 
- closes #27

### CODE REVIEW

**Comment by Remi-Gau** [comment]
Not sure if this should go in the changelog as it in practices fixes some bugs?=.

**Comment by htwangtw** [comment]
> Not sure if this should go in the changelog as it in practices fixes some bugs?

yep

**Comment by htwangtw** [comment]
and this made me realised i didn't update change log in the previous bug fix

**Review by htwangtw — APPROVED** [review]
Let's go ahead and merge this.... we can fix the change logs later

**Pull request merged**
