### PR TITLE
First working version

### PR DESCRIPTION
**Pull request by htwangtw**
## Points for review:
- General organisation
- Design choices
- Where should things go (i.e. the `tools/` directory)
- How to make the set up more streamlined for user. Currently the default requires users to download the templateflow archive and populate it with customised atlas.

## Features

Given a fMRIPrep derivative:
- generate subject level connectomes and time series
- generate group level time series
- output as hdf5 
- BIDS-app interface

## Limitations
- All scans within the dataset should share the same acquisition protocol.
- No customised atlas / strategy from user

## Need help
- Error code and error catching
- Versioning and release
- Create `Dockerfile` to handle the environment and the default atlas (download script in tool)
- ~use workflow engine to parallelise subject level process?~ ~joblib~ Not implementing until we have more clarity.
- ~allow users to change atlas / denoising setting from command line interface?~ think about how to pass config file

### CODE REVIEW

**Comment by pbellec** [comment]
re points of discussion:
1. worflow engine, I would strongly vote against. Workflow engines are a mess to configure, and they are a fast-moving landscape. I think it is much better to let users implement the parallelization if they wish to. 
2. command line interface is a bit tougher. I like the idea of config files (a lot), but I also would like to stick to the bids-app specs. If we are to move away from vanilla bids-app syntax, I would be in favor of using a framework, such as [boutiques](https://boutiques.github.io/) or [hydra](https://hydra.cc/docs/intro/).

otherwise, is the code ready for review?

**Comment by htwangtw** [comment]
I cannot find a reduced dataset to set a proper ci up. If people are fine with the lack of smoke test, it's almost ready to review

**Comment by htwangtw** [comment]
Parallel time series generation turns out to be a bad idea, because writing into the same HDF5 file in parallel is non-trivial. 
It might not even be needed as the run time is pretty short. I am using one dataset with 58 scans for smoke test. For MIST, it takes 20 minutes to create the output, including indexing the BIDS directory. For DiFuMo, it's 40 minutes. If the BIDS layout and the masks are pregenerated, the run time won't be crazy.

**Comment by htwangtw** [comment]
merge to main for now and will work on some features needed for UKBB

**Pull request merged**
